name: Script de download e extração dos Diários Oficiais

on:
  schedule:
    - cron: '10 14 * * 1-5'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install PyPDF2

    - name: Run Python script
      run: python src/pdf_downloader.py && python src/list_dir.py && python src/readpdf.py && python src/counter.py && python src/remove_pdf.py

    - name: Commit and push updated last date
      run: |
        git config user.name "Github Actions"
        git config user.email "actions@users.noreply.github.com"
        git pull origin main
        git add --all
        git commit -m "[CI] As Licitações do dia foram extraídas!"
        git push
